version: '3.1'

services:

  db:
    image: mariadb
    container_name: last_spike_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: spikeuser
      MYSQL_PASSWORD: spikepassword

    ports:
      - 127.0.0.1:3306:3306

