// <auto-generated />
using LastSpikeApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LastSpikeApi.Migrations
{
    [DbContext(typeof(LastSpikeContext))]
    [Migration("20191022115126_AddData")]
    partial class AddData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LastSpikeApi.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Latitude = 53.4854713,
                            Longitude = -2.2507676000000001,
                            Name = "example1"
                        },
                        new
                        {
                            UserID = 2,
                            Latitude = 53.475851200000001,
                            Longitude = -2.2485708999999998,
                            Name = "example2"
                        },
                        new
                        {
                            UserID = 3,
                            Latitude = 53.488216299999998,
                            Longitude = -2.2352457000000001,
                            Name = "example3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
